### ISSUE TITLE
I can't use at all

### ISSUE THREAD

**Issue by search4banlan** [mueslo/pythonBits#119]
I setup pythonbits via pip. However, whatever I input, it come out with errors.
This happens when I input "pythonbits -h"

```
Traceback (most recent call last):
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\config.py", line 48, in get
    return self._config.get(section, option)
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Tracker'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Marcia\AppData\Local\Programs\Python\Python39\Scripts\pythonbits.exe\__main__.py", line 4, in <module>
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\__main__.py", line 6, in <module>
    from . import bb
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\bb.py", line 23, in <module>
    from . import tvdb
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\tvdb.py", line 5, in <module>
    from .api_utils import d
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\api_utils.py", line 6, in <module>
    seed = config.get('Tracker', 'domain').encode('utf8')
  File "c:\users\marcia\appdata\local\programs\python\python39\lib\site-packages\pythonbits\config.py", line 52, in get
    reg_option = self.registry[(section, option)]
KeyError: ('Tracker', 'domain')
```

I have no idea what's wrong with it. I am using Python 3.9 in Windows 10.

**Comment by znedw** [comment]
i don't think I've ever successfully ran it on windows either

**Comment by search4banlan** [comment]
I install  "requests-cache". The problem is solved now.

**Comment by search4banlan** [comment]
I install "requests-cache". The problem is solved now.

**Comment by search4banlan** [comment]
I install "requests-cache". The problem is solved now.
