### ISSUE TITLE
Current repo breaks shell

### ISSUE THREAD

**Issue by Reverse256** [mueslo/pythonBits#122]
## **Description**
(This is not a big issue for me)

Fresh install of debian 10.
Use the current cloned repo installed via pip3

Might have to ctrl + C to duplicate.

I usually get this behavior after 1-3 uploads. Afterwards, I cannot see what I am typing in the shell and stdout doesn't start on a new line. I start a new shell instance to remedy this.

In the below example I do: 'echo foo' 'ls' 'rm echo' (no idea how it did 'touch echo' haha)

Finalize these values? This will upload or submit all necessary data. [y/n] [2021-09-18 12:12:10.839462] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/user/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/__main__.py", line 144, in main
    _main(Category, set_fields, get_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/__main__.py", line 131, in _main
    if headless or sub.confirm_finalization(get_fields):
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/bb.py", line 67, in confirm_finalization
    fields or self.default_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 259, in confirm_finalization
    choice = input('Finalize these values? This will upload or '
KeyboardInterrupt
user@public:/dev/shm$ hi
user@public:/dev/shm$ hi
user@public:/dev/shm$ asdf
user@public:/dev/shm$  echo  'dir1'  'dir2'
user@public:/dev/shm$  echo  'dir1'  'dir2'
user@public:/dev/shm$  echo  'dir1'  'dir2'
user@public:/dev/shm$ total 0
drwxrwxrwt  4 root root  100 Sep 18 05:08  .
drwxr-xr-x 17 root root 3160 Sep 18 00:24  ..
-rw-r--r--  1 user user    0 Sep 18 04:56  echo
drwxr-xr-x  2 user user 1020 Sep 18 00:29 'dir1'
drwxr-xr-x  2 user user  120 Sep 18 00:39 'dir2'
user@public:/dev/shm$ user@public:/dev/shm$ 'dir1'  'dir2'
user@public:/dev/shm$ total 0
drwxrwxrwt  4 root root   80 Sep 18 05:14  .
drwxr-xr-x 17 root root 3160 Sep 18 00:24  ..
drwxr-xr-x  2 user user 1020 Sep 18 00:29 'dir1'
drwxr-xr-x  2 user user  120 Sep 18 00:39 'dir2'

## **Additional context**
 - `pythonbits` version: i cloned the repo ~15 hours ago

## **Full log**
Likely is not the log that started the bug. I can reply with a new log the next time i use pythonbits.

[2021-09-18 12:15:52.991081] DEBUG: pythonBits: BbSubmission adding mapper scene for scene (checkbox)
[2021-09-18 12:15:52.991228] DEBUG: pythonBits: BbSubmission adding mapper torrentfile for file_input (file)
[2021-09-18 12:15:52.991296] DEBUG: pythonBits: BbSubmission adding mapper form_type for type (text)
[2021-09-18 12:15:52.991351] DEBUG: pythonBits: BbSubmission adding mapper form_submit for submit (text)
[2021-09-18 12:15:52.991650] DEBUG: pythonBits: VideoSubmission adding mapper tags for tags (text)
[2021-09-18 12:15:52.991720] DEBUG: pythonBits: VideoSubmission adding mapper cover for image (text)
[2021-09-18 12:15:52.991838] DEBUG: pythonBits: TvSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.991883] DEBUG: pythonBits: TvSubmission adding mapper form_description for desc (text)
[2021-09-18 12:15:52.991946] DEBUG: pythonBits: TvSubmission adding mapper form_description for desc (text)
[2021-09-18 12:15:52.992048] DEBUG: pythonBits: EpisodeSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.992093] DEBUG: pythonBits: EpisodeSubmission adding mapper form_description for desc (text)
[2021-09-18 12:15:52.992144] DEBUG: pythonBits: EpisodeSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.992245] DEBUG: pythonBits: SeasonSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.992290] DEBUG: pythonBits: SeasonSubmission adding mapper form_description for desc (text)
[2021-09-18 12:15:52.992339] DEBUG: pythonBits: SeasonSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.992477] DEBUG: pythonBits: MovieSubmission adding mapper source for source (text)
[2021-09-18 12:15:52.992530] DEBUG: pythonBits: MovieSubmission adding mapper video_codec for videoformat (text)
[2021-09-18 12:15:52.992586] DEBUG: pythonBits: MovieSubmission adding mapper audio_codec for audioformat (text)
[2021-09-18 12:15:52.992626] DEBUG: pythonBits: MovieSubmission adding mapper container for container (text)
[2021-09-18 12:15:52.992722] DEBUG: pythonBits: MovieSubmission adding mapper resolution for resolution (text)
[2021-09-18 12:15:52.992761] DEBUG: pythonBits: MovieSubmission adding mapper form_release_info for remaster_title (text)
[2021-09-18 12:15:52.992799] DEBUG: pythonBits: MovieSubmission adding mapper mediainfo for release_desc (text)
[2021-09-18 12:15:52.992842] DEBUG: pythonBits: MovieSubmission adding mapper screenshots for <function MovieSubmission.<lambda> at 0x7fc3ce0f39d8> (text)
[2021-09-18 12:15:52.992902] DEBUG: pythonBits: MovieSubmission adding mapper form_title for title (text)
[2021-09-18 12:15:52.992950] DEBUG: pythonBits: MovieSubmission adding mapper year for year (text)
[2021-09-18 12:15:52.993001] DEBUG: pythonBits: MovieSubmission adding mapper form_description for desc (text)
[2021-09-18 12:15:52.993110] DEBUG: pythonBits: AudioSubmission adding mapper format for format (text)
[2021-09-18 12:15:52.993161] DEBUG: pythonBits: AudioSubmission adding mapper bitrate for bitrate (text)
[2021-09-18 12:15:52.993209] DEBUG: pythonBits: AudioSubmission adding mapper cover for image (text)
[2021-09-18 12:15:52.993261] DEBUG: pythonBits: AudioSubmission adding mapper year for year (text)
[2021-09-18 12:15:52.993307] DEBUG: pythonBits: AudioSubmission adding mapper description for album_desc (text)
[2021-09-18 12:15:52.993355] DEBUG: pythonBits: AudioSubmission adding mapper release_desc for release_desc (text)
[2021-09-18 12:15:52.993398] DEBUG: pythonBits: AudioSubmission adding mapper scene for scene (checkbox)
[2021-09-18 12:15:52.993512] DEBUG: pythonBits: AudiobookSubmission adding mapper form_tags for tags (text)
[2021-09-18 12:15:52.993569] DEBUG: pythonBits: AudiobookSubmission adding mapper title for title (text)
[2021-09-18 12:15:52.993805] DEBUG: pythonBits: MusicSubmission adding mapper remaster for remaster_true (checkbox)
[2021-09-18 12:15:52.993857] DEBUG: pythonBits: MusicSubmission adding mapper remaster_year for remaster_year (text)
[2021-09-18 12:15:52.993925] DEBUG: pythonBits: MusicSubmission adding mapper remaster_title for remaster_title (text)
[2021-09-18 12:15:52.993970] DEBUG: pythonBits: MusicSubmission adding mapper media for media (text)
[2021-09-18 12:15:52.994016] DEBUG: pythonBits: MusicSubmission adding mapper form_tags for tags (text)
[2021-09-18 12:15:52.994060] DEBUG: pythonBits: MusicSubmission adding mapper artist for artist (text)
[2021-09-18 12:15:52.994102] DEBUG: pythonBits: MusicSubmission adding mapper title for title (text)
[2021-09-18 12:15:52.995618] DEBUG: pythonBits: Arguments: Namespace(category=None, data_method='auto', fields=['submit', 'torrentfile'], fields_ex=[], headless=False, num_cast=10, num_directors=2, num_screenshots=2, path='series name/', set_field=[], title=None, v=0)
[2021-09-18 12:15:52.995744] DEBUG: pythonBits: Creating cached renderer {'options': {'num_screenshots': 2, 'num_cast': 10, 'num_directors': 2, 'data_method': 'auto'}, 'path': '/dev/shm/series name', 'title_arg': None}
[2021-09-18 12:15:53.021927] DEBUG: pythonBits: Rendering field BbSubmission['submit']
[2021-09-18 12:15:53.022325] DEBUG: pythonBits: Adding BbSubmission dependency submit -> scene
[2021-09-18 12:15:53.022378] DEBUG: pythonBits: Rendering field BbSubmission['scene']
[2021-09-18 12:15:53.022776] DEBUG: pythonBits: Adding BbSubmission dependency scene -> path
[2021-09-18 12:16:02.094556] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/user/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 110, in __getitem__
    return self.fields[field]
KeyError: 'submit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 110, in __getitem__
    return self.fields[field]
KeyError: 'scene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/__main__.py", line 144, in main
    _main(Category, set_fields, get_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/__main__.py", line 119, in _main
    sub.show_fields(get_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/bb.py", line 63, in show_fields
    fields or self.default_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 241, in show_fields
    val = self[field]
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 120, in __getitem__
    rv = field_renderer()
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 204, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/bb.py", line 63, in show_fields
    fields or self.default_fields)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 241, in show_fields
    val = self[field]
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/submission.py", line 120, in __getitem__
    rv = field_renderer()
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/bb.py", line 128, in _render_scene
    query_scene_fname(path)
  File "/home/user/.local/lib/python3.7/site-packages/pythonbits/scene.py", line 73, in query_scene_fname
    r = requests.get(srrdb + "api/search/{}".format(query))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 271, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by Reverse256** [comment]
[pythonbits.log](https://github.com/mueslo/pythonBits/files/7214478/pythonbits.log)

Here's a log that is the first run of pb after booting the computer and the local shell's text isn't viewable for subsequent commands.
