### ISSUE TITLE
ValueError: _type_ 'v' not supported

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#22]
```
Traceback (most recent call last):
  File "/usr/local/bin/pythonbits", line 9, in <module>
    load_entry_point('pythonbits==3.0b5', 'console_scripts', 'pythonbits')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 8, in <module>
    from . import bb
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 23, in <module>
    from .submission import Submission, form_field, finalize
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 8, in <module>
    import readline
  File "/usr/local/lib/python2.7/site-packages/readline.py", line 6, in <module>
    from pyreadline.rlmain import Readline
  File "/usr/local/lib/python2.7/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/usr/local/lib/python2.7/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/usr/local/lib/python2.7/site-packages/pyreadline/clipboard/win32_clipboard.py", line 37, in <module>
    import ctypes.wintypes as wintypes
  File "/usr/local/lib/python2.7/ctypes/wintypes.py", line 23, in <module>
    class VARIANT_BOOL(_SimpleCData):
ValueError: _type_ 'v' not supported
```

**Comment by eeeeeeeeeve** [comment]
Oh, er, I'm on Ubuntu

**Comment by eeeeeeeeeve** [comment]
Nevermind I just did `pip install readline`

**Comment by mueslo** [comment]
That's strange, the readline module should be part of the Python standard library: https://docs.python.org/2/library/readline.html

Edit: seems to be a Ubuntu-related thing: https://stackoverflow.com/questions/15975567/python-2-7-4-on-ubuntu-10-04-import-readline-errortried-many-ways-never-work
