### ISSUE TITLE
KeyError: 'year'

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#26]
```
Traceback (most recent call last):
  File "/usr/local/bin/pythonbits", line 9, in <module>
    load_entry_point('pythonbits==3.0b5', 'console_scripts', 'pythonbits')()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 110, in main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 248, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 119, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 211, in _render_submit
    return self.show_fields(self.registry['mappers'].keys())
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 248, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 119, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 515, in _render_year
    return self['guess']['year']
KeyError: 'year'
```

Instead of throwing a KeyError, can it just prompt me if guessit can't find it?

**Comment by mueslo** [comment]
Yes it could, but that would make too much sense.
