### ISSUE TITLE
Upgraded to rc-1

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#28]
```
Traceback (most recent call last):
  File "/usr/local/bin/pythonbits", line 9, in <module>
    load_entry_point('pythonbits==3.0rc1', 'console_scripts', 'pythonbits')()
TypeError: main() takes exactly 3 arguments (0 given)
```

**Comment by mueslo** [comment]
oops, I'll fix this when I get back to my computer later today

**Comment by eeeeeeeeeve** [comment]
Nope :(

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 135, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 112, in _main
    sub.show_fields(get_fields or sub.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 250, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 123, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 213, in _render_submit
    return self.show_fields(self.registry['mappers'].keys())
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 250, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 123, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 91, in _render_form_type
    return self._form_type
AttributeError: 'BbSubmission' object has no attribute '_form_type'
```

**Comment by eeeeeeeeeve** [comment]
```
[2018-02-26 03:38:40.921127] DEBUG: pythonBits: BbSubmission adding mapper torrentfile for file_input (file)
[2018-02-26 03:38:40.921580] DEBUG: pythonBits: BbSubmission adding mapper scene for scene (checkbox)
[2018-02-26 03:38:40.921815] DEBUG: pythonBits: BbSubmission adding mapper form_submit for submit (text)
[2018-02-26 03:38:40.922028] DEBUG: pythonBits: BbSubmission adding mapper form_type for type (text)
[2018-02-26 03:38:40.923611] DEBUG: pythonBits: VideoSubmission adding mapper tags for tags (text)
[2018-02-26 03:38:40.923924] DEBUG: pythonBits: VideoSubmission adding mapper cover for image (text)
[2018-02-26 03:38:40.924501] DEBUG: pythonBits: TvSubmission adding mapper form_title for title (text)
[2018-02-26 03:38:40.924703] DEBUG: pythonBits: TvSubmission adding mapper form_description for desc (text)
[2018-02-26 03:38:40.924939] DEBUG: pythonBits: TvSubmission adding mapper form_title for title (text)
[2018-02-26 03:38:40.925158] DEBUG: pythonBits: TvSubmission adding mapper form_description for desc (text)
[2018-02-26 03:38:40.925607] DEBUG: pythonBits: MovieSubmission adding mapper source for source (text)
[2018-02-26 03:38:40.926063] DEBUG: pythonBits: MovieSubmission adding mapper container for container (text)
[2018-02-26 03:38:40.926252] DEBUG: pythonBits: MovieSubmission adding mapper form_release_info for remaster_title (text)
[2018-02-26 03:38:40.926439] DEBUG: pythonBits: MovieSubmission adding mapper audio_codec for audioformat (text)
[2018-02-26 03:38:40.926616] DEBUG: pythonBits: MovieSubmission adding mapper mediainfo for release_desc (text)
[2018-02-26 03:38:40.926806] DEBUG: pythonBits: MovieSubmission adding mapper video_codec for videoformat (text)
[2018-02-26 03:38:40.926983] DEBUG: pythonBits: MovieSubmission adding mapper resolution for resolution (text)
[2018-02-26 03:38:40.927165] DEBUG: pythonBits: MovieSubmission adding mapper screenshots for <function <lambda> at 0x7f5643dd81b8> (text)
[2018-02-26 03:38:40.927447] DEBUG: pythonBits: MovieSubmission adding mapper form_title for title (text)
[2018-02-26 03:38:40.927675] DEBUG: pythonBits: MovieSubmission adding mapper form_description for desc (text)
[2018-02-26 03:38:40.927903] DEBUG: pythonBits: MovieSubmission adding mapper year for year (text)
[2018-02-26 03:38:40.932438] DEBUG: pythonBits: Arguments: Namespace(category=None, fields=['submit'], fields_ex=[], num_cast=5, num_screenshots=2, path='RESCINDED', set_field=[], title='crashing 2017', v=0)
[2018-02-26 03:38:40.932840] DEBUG: pythonBits: Creating cached renderer {'path': '/home/eeeeve/rtorrent/downloads/data/RESCINDED', '
title_arg': 'crashing 2017', 'options': {'num_cast': 5, 'num_screenshots': 2}}
[2018-02-26 03:38:41.029843] DEBUG: pythonBits: Adding BbSubmission dependency submit -> form_type
[2018-02-26 03:38:41.030135] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 135, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 112, in _main
    sub.show_fields(get_fields or sub.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 250, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 123, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 213, in _render_submit
    return self.show_fields(self.registry['mappers'].keys())
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 250, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 123, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 91, in _render_form_type
    return self._form_type
AttributeError: 'BbSubmission' object has no attribute '_form_type'
```
