### ISSUE TITLE
Skip rating if no ratings on IMDB

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#38]
```
[2018-06-01 07:59:10.097767] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 138, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 114, in _main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 42, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 42, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 165, in _render_tags
    tags = list(self['summary']['genres'])
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 552, in _render_summary
    return movie.summary()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/imdb.py", line 36, in summary
    'rating': (self.movie.ratings.rating, 10),
  File "/usr/local/lib/python2.7/site-packages/attrdict/mixins.py", line 82, in __getattr__
    cls=self.__class__.__name__, name=key
AttributeError: 'AttrDict' instance has no attribute 'rating'
```

Replicate with tt5639898

**Comment by mueslo** [comment]
Related to #29
