### ISSUE TITLE
Can't handle redirection IMDB IDs

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#39]
```
[2018-06-01 08:01:40.507497] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 138, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 114, in _main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 42, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 42, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 498, in _render_form_description
    bb.section("Screenshots", bb.center(ss)) +
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 488, in _render_description
    ("Information", self['section_information'])]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 441, in _render_section_information
    rating, votes = i.get_rating(s['imdb_id'])
  File "/usr/local/lib/python2.7/site-packages/pythonbits/imdb.py", line 55, in get_rating
    res = self.imdb.get_title_ratings(imdb_id)
  File "/usr/local/lib/python2.7/site-packages/imdbpie/imdbpie.py", line 130, in get
    self._redirection_title_check(imdb_id)
  File "/usr/local/lib/python2.7/site-packages/imdbpie/imdbpie.py", line 328, in _redirection_title_check
    msg='{0} is a redirection imdb id'.format(imdb_id)
  File "/usr/local/lib/python2.7/site-packages/imdbpie/imdbpie.py", line 351, in _title_not_found
    raise LookupError('Title not found.{0}'.format(msg))
LookupError: Title not found. tt7246802 is a redirection imdb id
```

reproduce with Legion.S02E09

**Comment by mueslo** [comment]
This is an issue with imdbpie or the data present in thetvdb. If there's more than just a singular instance of this occurring, I can invest some time in a workaround though.

**Comment by jseycom** [comment]
Ready Player One:

LookupError: Title not found. tt1677720 is a redirection imdb id

**Comment by mueslo** [comment]
`tt1677720` isn't a redirection id, can't reproduce.

**Comment by vsego** [comment]
I had this error for all IMDB `tt*` IDs I've used, but `pip install imdbpie --upgrade` resolved the problem for me.
