### ISSUE TITLE
Overflow error when scene checking

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#42]
```
[2018-06-01 19:22:20.482170] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 142, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 118, in _main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 77, in _render_scene
    return is_scene_crc(path)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/scene.py", line 30, in is_scene_crc
    buf = crc32(buf) & 0xFFFFFFFF
OverflowError: size does not fit in an int
```

**Comment by mueslo** [comment]
Can you retest with the latest commits?

**Comment by eeeeeeeeeve** [comment]
Seemingly resolved!
