### ISSUE TITLE
mktorrent issue (already install 1.1)

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#44]
```
mktorrent 1.1 (c) 2007, 2009 Emil Renner Berthing

mktorrent: invalid option -- '-'
Use -h for help.
[2018-06-03 03:50:16.441121] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 142, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 118, in _main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 97, in _render_torrentfile
    return make_torrent(self['path'])
  File "/usr/local/lib/python2.7/site-packages/pythonbits/mktorrent.py", line 70, in make_torrent
    raise MkTorrentException()
MkTorrentException
```

**Comment by eeeeeeeeeve** [comment]
```
mktorrent -h
mktorrent 1.1 (c) 2007, 2009 Emil Renner Berthing

Usage: mktorrent [OPTIONS] <target directory or filename>

Options:
-a <url>[,<url>]* : specify the full announce URLs
                    at least one is required
                    additional -a adds backup trackers
-c <comment>      : add a comment to the metainfo
-d                : don't write the creation date
-h                : show this help screen
-l <n>            : set the piece length to 2^n bytes,
                    default is 18, that is 2^18 = 256kb
-n <name>         : set the name of the torrent,
                    default is the basename of the target
-o <filename>     : set the path and filename of the created file
                    default is <name>.torrent
-p                : set the private flag
-s                : add source string embedded in infohash
-v                : be verbose
-w <url>[,<url>]* : add web seed URLs
                    additional -w adds more URLs

Please send bug reports, patches, feature requests, praise and
general gossip about the program to: mktorrent@rudde.org
```

also:

```[2018-06-04 05:20:12.894209] DEBUG: pythonBits: Adding MovieSubmission dependency submit -> scene
[2018-06-04 05:20:12.894442] DEBUG: pythonBits: Rendering field MovieSubmission['scene']
[2018-06-04 05:20:12.896237] DEBUG: pythonBits: Adding MovieSubmission dependency scene -> path
[2018-06-04 05:20:12.896525] DEBUG: pythonBits: Calculating CRC32 value
[2018-06-04 05:20:17.519354] DEBUG: pythonBits: CRC32 EEA2AD6E
[2018-06-04 05:20:18.972874] INFO: pythonBits: Scene checkbox set to False due to CRC query result
[2018-06-04 05:20:18.973362] DEBUG: pythonBits: No rule for formatting <type 'bool'> False
[2018-06-04 05:20:18.975028] DEBUG: pythonBits: Adding MovieSubmission dependency submit -> source
[2018-06-04 05:20:18.975244] DEBUG: pythonBits: Rendering field MovieSubmission['source']
[2018-06-04 05:20:18.976998] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:18.978700] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:18.980405] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:18.982087] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:18.983789] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:18.985486] DEBUG: pythonBits: Adding MovieSubmission dependency source -> path
[2018-06-04 05:20:23.144443] DEBUG: pythonBits: No rule for formatting <type 'unicode'> WEB-DL
[2018-06-04 05:20:23.146145] DEBUG: pythonBits: Adding MovieSubmission dependency submit -> torrentfile
[2018-06-04 05:20:23.146365] DEBUG: pythonBits: Rendering field MovieSubmission['torrentfile']
[2018-06-04 05:20:23.148151] DEBUG: pythonBits: Adding MovieSubmission dependency torrentfile -> path
[2018-06-04 05:20:23.157551] INFO: pythonBits: Waiting for torrent creation to complete...
[2018-06-04 05:20:23.158205] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/eeeeve/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 142, in main
    _main(Category, set_fields, get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/__main__.py", line 118, in _main
    sub.show_fields(get_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 44, in show_fields
    fields or self.default_fields)
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/usr/local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/usr/local/lib/python2.7/site-packages/pythonbits/bb.py", line 97, in _render_torrentfile
    return make_torrent(self['path'])
  File "/usr/local/lib/python2.7/site-packages/pythonbits/mktorrent.py", line 70, in make_torrent
    raise MkTorrentException()
MkTorrentException
```
