### ISSUE TITLE
UnicodeDecodeError in filename

### ISSUE THREAD

**Issue by eeeeeeeeeve** [mueslo/pythonBits#48]
```
Traceback (most recent call last):
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/__main__.py", line 142, in main
    _main(Category, set_fields, get_fields)
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/__main__.py", line 118, in _main
    sub.show_fields(get_fields)
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/bb.py", line 51, in show_fields
    fields or self.default_fields)
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 205, in _render_submit
    return self.show_fields(list(self.registry['mappers'].keys()))
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/bb.py", line 51, in show_fields
    fields or self.default_fields)
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 242, in show_fields
    val = self[field]
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/bb.py", line 518, in _render_form_description
    ss = "".join(map(bb.img, self['screenshots']))
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/bb.py", line 217, in _render_screenshots
    ffmpeg = FFMpeg(self['mediainfo_path'])
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/submission.py", line 121, in __getitem__
    rv = field_renderer()
  File "/home/eeeeve/.local/lib/python2.7/site-packages/pythonbits/bb.py", line 205, in _render_mediainfo_path
    print("{}: {}".format(k, os.path.relpath(v, self['path'])))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
```

`The.Last.Man.On.Earth.S04E12.Señor.Clean`

**Comment by mueslo** [comment]
I think this is fixed
