### ISSUE TITLE
Bad Request for url: https://api.imgur.com//oauth2/token

### ISSUE THREAD

**Issue by plotski** [mueslo/pythonBits#77]
imgur uploading worked fine, but it stopped working with current master:

Enter a provider for image hosting, supported options are ptpimg or imgur: imgur
Would you like to save this value in /home/ich/.config/pythonbits/pythonbits.cfg? [Y/n] n
[2020-06-13 10:58:56.792972] ERROR: pythonBits: An exception occured.
Full log stored at file:///home/ich/.cache/pythonbits/log/pythonbits.log
Traceback (most recent call last):
  File "/home/ich/code/pythonBits/pythonbits/__main__.py", line 137, in main
    _main(Category, set_fields, get_fields)
  File "/home/ich/code/pythonBits/pythonbits/__main__.py", line 125, in _main
    sub.finalize()
  File "/home/ich/code/pythonBits/pythonbits/submission.py", line 214, in finalize
    self[f] = getattr(self, '_finalize_' + f)()
  File "/home/ich/code/pythonBits/pythonbits/bb.py", line 300, in _finalize_screenshots
    return imagehosting.upload_files(*self['screenshots'])
  File "/home/ich/code/pythonBits/pythonbits/imagehosting.py", line 16, in upload_files
    return ImgurUploader().upload(*images)
  File "/home/ich/code/pythonBits/pythonbits/imgur.py", line 78, in upload
    self.imgur_auth.prepare()
  File "/home/ich/code/pythonBits/pythonbits/imgur.py", line 29, in prepare
    self.refresh_access_token()
  File "/home/ich/code/pythonBits/pythonbits/imgur.py", line 46, in refresh_access_token
    self.fetch_access_token('refresh_token', self.refresh_token)
  File "/home/ich/code/pythonBits/pythonbits/imgur.py", line 57, in fetch_access_token
    res.raise_for_status()
  File "/home/ich/code/pythonBits/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.imgur.com//oauth2/token

**Comment by mueslo** [comment]
Interesting, currently works fine for me. Investigating.

**Comment by mueslo** [comment]
Ah, pretty sure this is due to the breaking change here: https://github.com/mueslo/pythonBits/blob/master/CHANGELOG.md#31. Please test to see if that fixes it. I guess I could try to write some migration code to delete the imgur section if it still contains the API key, so that not everyone runs into this.

**Comment by plotski** [comment]
My bad, that was it.

Thanks.

**Comment by mueslo** [comment]
I have some rudimentary migration code locally which I'll push later.
